### PR TITLE
Fix fractional faculty loads bug and add total hours to table

### LINKED ISSUE #103: Add total row to bottom of load table
Department chairs are given a "budget" of faculty load to spend on the schedule, so it would be nice to see a total row at the bottom.

### LINKED ISSUE #126: Fractional load hours are not supported
Teaching load hours are not computed correctly for courses with fractional teaching loads (e.g., CS 396 is 2 credit hours for students but only 0.25 credit hours for the instructor, and CS X95 are 0.5 each).

Derek Schuurman's teaching load in the 2021-22 schedule doesn't add in load hours for CS X95 or CS 396/8, though both values are included in the CSV input.

### PR DESCRIPTION
**Pull request by Jdellis818**
This PR fixes the bug where fractional faculty loads are set to 0. It also fixes a bug where faculty loads for sections with multiple professors were miscalculated and adds a total to the loads table. To test, import a schedule with fractional faculty loads. It should successfully compute the loads in the table and be successfully added to an exported spreadsheet.

### CODE REVIEW

File: client-course-schedulizer/src/utilities/helpers/caseFunctions.ts [hunk 1]
```diff
@@ -134,12 +134,14 @@ export const yearCallback = (value: string, { section }: CaseCallbackParams) =>
   section.year = yearCase(value);
 };
 
-export const studentHoursCallback = (value: string, { course }: CaseCallbackParams) => {
-  course.studentHours = numberDefaultZeroCase(value);
+export const studentHoursCallback = (value: string, { section }: CaseCallbackParams) => {
+  section.studentHours = value.startsWith("$")
```
Comment (Jdellis818) [inline client-course-schedulizer/src/utilities/helpers/caseFunctions.ts:138]: This was a little bug with excel I was getting that was prepending $ to the student and faculty hours. I figured it'd be good just to take it out since professors may have a similar issue

File: client-course-schedulizer/src/utilities/helpers/caseFunctions.ts [hunk 2]
```diff
@@ -333,7 +335,7 @@ export const prefixCase = (value: string): string[] => {
   return value.replace(" ", "").split(/[;,\n]/);
 };
 
-export const numberDefaultZeroCase = (value: string): number => {
+export const integerDefaultZeroCase = (value: string): number => {
```
Comment (Jdellis818) [inline client-course-schedulizer/src/utilities/helpers/caseFunctions.ts:338]: I changed the name of this function to specify that it should only be used for integers. It was the source of the fractional loads bug.

File: client-course-schedulizer/csv/math-schedule-export.csv [hunk 3]
```diff
@@ -51,7 +51,7 @@ T","10:30AM - 11:20AM
 19/FA,"MATH-359-A",3.00,2.00,"NH 294","TH","6:00PM - 9:00PM","Sem: Sec Teaching of Math","David Klanderman"
 19/FA,"MATH-361-A",4.00,4.00,"NH 251","MTWF","12:30PM - 1:20PM","Real Analysis I","John Ferdinands"
 20/IN,"MATH-390-A",3.00,0.00,"","","","Modeling of Angiogenesis","Todd Kapitula"
-19/FA,"MATH-390-A",3.00,0.00,"","","","Modeling of Angiogenesis","Christopher Moseley"
+19/FA,"MATH-390-A",1.00,0.00,"","","","Modeling of Angiogenesis","Christopher Moseley"
```
Comment (Jdellis818) [inline client-course-schedulizer/csv/math-schedule-export.csv:54]: I'm not sure why, but our test file had this 1 as a 3. I checked the original file and it should be a 1. It makes me a little worried that there could be other data in our tests that are incorrect.

File: client-course-schedulizer/src/utilities/services/facultyLoadsService.ts [hunk 4]
```diff
@@ -57,7 +57,7 @@ const updateRow = ({
       : (prevRow[termCourseSectionProp] = sectionName);
 
     prevRow[termHoursProp] = prevRow[termHoursProp]
-      ? Number(prevRow[termHoursProp]) / section.instructors.length + facultyHours
+      ? Number(prevRow[termHoursProp]) + facultyHours
```
Comment (Jdellis818) [inline client-course-schedulizer/src/utilities/services/facultyLoadsService.ts:60]: This was causing a miscalculation of some faculty loads. This division already occurs in the calculation of `facultyHours` so it was unnecessary.

File: client-course-schedulizer/csv/math-schedule-export.csv (hunk 3 above)
Comment (bryantgeorge) [reply client-course-schedulizer/csv/math-schedule-export.csv:54]: Hmm, I must have missed this when I looked the test file over. Yeah, I really hope there aren't more of these... We've probably caught the vast majority by now though.

**Review by bryantgeorge — CHANGES_REQUESTED** [review]
Looks good, just one minor change that I think would be really helpful is if the Total Hours row summed the Fall, Spring, Summer, and Other hours separately as well.

**Comment by Jdellis818** [comment]
> Looks good, just one minor change that I think would be really helpful is if the Total Hours row summed the Fall, Spring, Summer, and Other hours separately as well.

@bryantgeorge Good call. I've now added that.

**Comment by bryantgeorge** [comment]
> > Looks good, just one minor change that I think would be really helpful is if the Total Hours row summed the Fall, Spring, Summer, and Other hours separately as well.
> 
> @bryantgeorge Good call. I've now added that.

**Review by bryantgeorge — APPROVED** [review]
LGTM (the totals row is really nice!)
